language: bash

services:
  - docker

env:
  - VERSION=2.4
  - VERSION=2.4 VARIANT=alpine

script:
  - cd ./"${VERSION:0:3}"/alpine
  - travis_retry make debug && make

after_success:
  - . "${TRAVIS_BUILD_DIR}/release.sh"
